export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOADING_PATIENTS = "LOADING_PATIENTS";
export const GET_PATIENTS = "GET_PATIENTS";
export const VIEW_PATIENT = "VIEW_PATIENT";
export const EDIT_PATIENT = "EDIT_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";

export const LOADING_VEHICLES = "LOADING_VEHICLES";
export const GET_VEHICLES = "GET_VEHICLES";
export const VIEW_VEHICLE = "VIEW_VEHICLE";
export const EDIT_VEHICLE = "EDIT_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const ADD_VEHICLE = "ADD_VEHICLE";

export const LOADING_PERSONNEL = "LOADING_PERSONNEL";
export const GET_PERSONNEL = "GET_PERSONNEL";
export const VIEW_PERSONNEL = "VIEW_PERSONNEL";
export const EDIT_PERSONNEL = "EDIT_PERSONNEL";
export const DELETE_PERSONNEL = "DELETE_PERSONNEL";
export const ADD_PERSONNEL = "ADD_PERSONNEL";

export const LOADING_TRIP = "LOADING_TRIP";
export const GET_TRIPS = "GET_TRIPS";
export const VIEW_TRIP = "VIEW_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const ADD_TRIP = "ADD_TRIP";

export const LOADING_SCHEDULE = "LOADING_SCHEDULE";
export const GET_SCHEDULES = "GET_SCHEDULES";
export const VIEW_SCHEDULE = "VIEW_SCHEDULE";
export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";

export const LOADING_SKILL = "LOADING_SKILL";
export const ADD_SKILL = "ADD_SKILL";
export const GET_ALL_SKILLS = "GET_ALL_SKILLS";
export const DELETE_SKILL = "DELETE_SKILL";

export const LOADING_STATION = "LOADING_STATION";
export const ADD_STATION = "ADD_STATION";
export const GET_ALL_STATIONS = "GET_ALL_STATIONS";
export const DELETE_STATION = "DELETE_STATION";
